## Variables

## Learning Objectives

1. Distinguish between basic data types and special data structures in Python
2. Demonstrate how to use lists and dictionaries
3. Demonstrate how to index/slice lists, strings, and NumPy arrays
4. Use for loops and list comprehensions to perform iterative procedures
5. Use conditional statements to implement logic flow
6. Utilize user-defined and library-imported functions

## What are Variables?

**Variables** are named references to values stored in memory. They allow you to store data and reuse it later in a program. In Python, variables are created when you assign a value to a name using the equals sign (`=`).

In [1]:
# Assign values to variables
age = 25
name = "Alice"

# Use variables in expressions
next_year_age = age + 1

print(name)
print(next_year_age)

Alice
26


## Basic Data Types

## Integer

An **integer** (`int`) is a basic numeric data type in Python used to represent whole numbers without a decimal point. Integers can be positive, negative, or zero and are commonly used for counting, indexing, and arithmetic operations.

In [2]:
apples = 10
oranges = 3

# Perform arithmetic with integers
total_fruit = apples + oranges
difference = apples - oranges

print(total_fruit)
print(difference)

13
7


## Float

A **float** (`float`) is a numeric data type used to represent numbers with decimal points. Floats are commonly used when working with measurements, averages, or any values that require fractional precision.

In [3]:
# Working with floats

price = 9.99
tax_rate = 0.08

total_price = price * (1 + tax_rate)
print(total_price)

10.789200000000001


## String

A **string** (`str`) in Python is a data type used to store text. Strings are created by placing characters inside `' '` or double quotes `" "`. They can contain letters, numbers, symbols, and spaces. Strings are immutable, meaning their contents cannot be changed after they are created.


In [4]:
# Creating strings
name = "Alice"
greeting = 'Hello, world!'

# Printing a string
print(name)
print(greeting)

# Combining strings (concatenation)
message = "Hello " + name
print(message)

Alice
Hello, world!
Hello Alice


## Boolean

A **boolean** (`bool`) in Python is a data type that represents one of two possible values: `True` or `False`. Booleans are commonly used to represent the result of comparisons or conditions and are often used in conditional statements and logical operations.

In [5]:
# Creating booleans
is_student = True
is_graduated = False

print(is_student)
print(is_graduated)

True
False


## Special Data Structures

## List

A **list** (`list`) in Python is a data structure used to store an ordered collection of items. Lists can contain values of any data type, including numbers, strings, and even other lists. Lists are mutable, meaning their contents can be changed after they are created. Lists are defined using square brackets `[]`.

In [6]:
# Creating a list
numbers = [1, 2, 3, 4]

# Creating a list with different data types
mixed_list = [10, "hello", True]

print(numbers)
print(mixed_list)

[1, 2, 3, 4]
[10, 'hello', True]


## List Methods: append() and pop()

Lists have built-in methods that allow you to **modify their contents**. The `.append(x)` method adds an element to the **end** of the list while `.pop()` removes and returns the **last element** of the list.

In [7]:
# Using append()
numbers = [1, 2, 3]
numbers.append(4)

print(numbers)  # [1, 2, 3, 4]

# Using pop()
last_item = numbers.pop()

print(numbers)   # [1, 2, 3]
print(last_item) # 4

[1, 2, 3, 4]
[1, 2, 3]
4


## Dictionary

A **dictionary** (`dict`) in Python is a data structure that stores data as **key–value pairs**. Each key is unique and is used to access its associated value. Dictionaries are mutable, meaning their contents can be changed after they are created. Dictionaries are defined using curly braces `{}`.

In [8]:
# Creating a dictionary
student = {
    "name": "Alice",
    "age": 21,
}

# Accessing values using keys
print(student["name"])

# Adding a new key-value pair
student["major"] = "Data Science"

# Modifying a value
student["age"] = 22

print(student)

Alice
{'name': 'Alice', 'age': 22, 'major': 'Data Science'}


## Indexing/Slices

## List Slice

A **list slice** in Python is a way to access a subset of elements from a list. Slicing is done using the syntax `[start:stop]`, where `start` is the index to begin from and `stop` is the index where slicing ends (not included). If `start` or `stop` are omitted, Python uses the beginning or end of the list.

In [9]:
# Creating a list
numbers = [10, 20, 30, 40, 50]

# Second item in list
print(numbers[1])

# Slice from index 1 up to (but not including) index 4
print(numbers[1:4])

# Slice from the beginning to index 3
print(numbers[:3])

# Slice from index 2 to the end
print(numbers[2:])

20
[20, 30, 40]
[10, 20, 30]
[30, 40, 50]


## String Slice

A **string slice** in Python is a way to extract a portion of a string using index positions. Slicing uses the syntax `[start:stop]`, where `start` is the index to begin from and `stop` is the index where the slice ends (not included). If `start` or `stop` are omitted, Python uses the beginning or end of the string.

In [10]:
# Creating a string
text = "Data Science"

# Third letter
print(text[2])

# Slice from index 0 up to (but not including) index 4
print(text[0:4])

# Slice from the beginning to index 4
print(text[:4])

# Slice from index 5 to the end
print(text[5:])

t
Data
Data
Science


## Operators

## Arithmetic Operators

**Arithmetic operators** in Python are symbols used to perform mathematical calculations on numbers. They allow you to add, subtract, multiply, divide, and raise numbers to powers.

In [11]:
# Example numbers
a = 10
b = 3
c = 6

# Addition and Subtraction
print(a + b - c)

# Multiplication and Division
print(a * b / c)

# Exponent (power)
print(a ** b)

7
5.0
1000


## Comparison Operators

**Comparison operators** in Python are used to compare two values. They return a boolean value (`True` or `False`) depending on whether the comparison is correct.

In [12]:
# Example numbers
x = 10
y = 5
z = 2

# Greater than
print(x > y)

# Less than or equal to
print(x <= y)

# Equal to
print(x == y)

# Not equal to
print(x != y)

True
False
False
True


## Conditionals

## Logic Flow (if-else)

**Logic flow (if-else)** in Python allows your program to make decisions based on conditions. An `if` statement checks whether a condition is `True`. If it is, the code inside the `if` block runs. If the condition is `False`, the code inside the `else` block runs instead.

In [13]:
# Example variable
age = 20

# Conditional statement
if age >= 18:
    print("You are an adult")
else:
    print("You are a minor")

You are an adult


## Boolean Conditionals (and/or)

**Boolean conditionals (`and` / `or`)** in Python allow you to combine multiple conditions in a single statement. The `and` operator returns `True` only if both conditions are `True`. The `or` operator returns `True` if at least one of the conditions is `True`.

In [14]:
# Example variables
age = 20
is_student = True

# Using 'and'
if age >= 18 and is_student:
    print("You are an adult student")

# Using 'or'
if age < 18 or is_student:
    print("You are either under 18 or a student")

You are an adult student
You are either under 18 or a student


## Loops

## For Loop

A **for loop** in Python is used to iterate over a sequence of items, such as a list, string, or range. During each iteration, the loop assigns the next item in the sequence to a variable and executes the code inside the loop.

In [15]:
# Looping through a list
numbers = [1, 2, 3]

for num in numbers:
    print(num)

# Looping using range
for i in range(2):
    print(i)

1
2
3
0
1


## For Loops with Strings

A **for loop** can also be used to iterate over a string. Since strings are sequences of characters, the loop will go through each character one at a time, assigning it to the loop variable.

In [16]:
## Looping through a string
word = "python"

for letter in word:
    print(letter)

p
y
t
h
o
n


## For Loops with Dictionaries

A **for loop** can be used to iterate over a dictionary. By default, the loop goes through the **keys**, but you can also loop through the **values** or both **keys and values** using dictionary methods.

In [17]:
# Looping through keys
student = {"name": "Alice", "age": 21}

for key in student:
    print(key)

# Looping through values
for value in student.values():
    print(value)

# Looping through key-value pairs
for key, value in student.items():
    print(key, value)

name
age
Alice
21
name Alice
age 21


## List Comprehensions

## List Comprehension

A **list comprehension** in Python is a concise way to create a new list by iterating over an existing sequence and optionally applying a transformation or condition. It combines a `for` loop and list creation into a single line of code.

In [18]:
# Create a list using a loop
squares = []
for i in range(5):
    squares.append(i ** 2)

print(squares)

# Create the same list using a list comprehension
squares = [i ** 2 for i in range(5)]
print(squares)

# List comprehension using a list with conditional statements
large_squares = [x for x in squares if x > 4]
print(large_squares)

[0, 1, 4, 9, 16]
[0, 1, 4, 9, 16]
[9, 16]


## Functions

## Function

A **function** in Python is a reusable block of code that performs a specific task. Functions help organize code, avoid repetition, and make programs easier to read and maintain. Functions are defined using the `def` keyword and can take inputs (parameters) and return outputs.

In [19]:
# Defining a function
def greet(name):
    print("Hello " + name)

# Calling the function
greet("Alice")
greet("Bob")

# Function that returns a value
def add_numbers(a, b):
    return a + b

result = add_numbers(3, 5)
print(result)

Hello Alice
Hello Bob
8


## Parameters, Arguments, and Return vs Print

A **parameter** is a variable defined in a function, while an **argument** is the value passed into the function when it is called.

The **return** statement sends a value back from a function so it can be stored or used later, while **print** only displays the value and does not store it.

## Libraries

## Library

A **library** in Python is a collection of pre-written code that provides useful functions, classes, and tools that you can use in your programs. Libraries help you avoid writing code from scratch and allow you to perform complex tasks more easily.

In [20]:
# Importing a library
import math

# Using a function from the library
print(math.sqrt(16))

# Importing a specific function from a library
from math import sqrt

print(sqrt(25))

4.0
5.0


## NumPy

## NumPy

**NumPy** is a Python library used for numerical computing. It provides a powerful data structure called the **NumPy array**, which allows you to store and operate on large collections of numbers efficiently. NumPy also includes many built-in functions for performing mathematical operations, statistical analysis, and linear algebra.

## NumPy Array

A **NumPy array** is the main data structure provided by NumPy for storing and working with numerical data. It is similar to a Python list, but it is designed to be more efficient and supports fast mathematical operations on entire arrays of numbers at once.

In [21]:
import numpy as np

# Creating a NumPy array
arr1d = np.array([1, 2, 3, 4])

print(arr1d)

# Performing operations on the entire array
print(arr1d + 10)

# Multiplying every element
print(arr1d * 2)

[1 2 3 4]
[11 12 13 14]
[2 4 6 8]


## 2D NumPy Arrays

A **2D NumPy array** is a NumPy array that stores data in two dimensions, similar to a table with rows and columns. These arrays are commonly used to represent matrices, datasets, or grids of numerical values. You can access elements using row and column indices.

In [22]:
# Creating a 2D NumPy array
arr2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(arr2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Indexing 2D NumPy Arrays

In [23]:
# Accessing an element (row 2, column 3)
print(arr2d[1, 2])

# Accessing a full row
print(arr2d[0])

# Accessing a full column
print(arr2d[:, 1])

6
[1 2 3]
[2 5 8]


## Slicing NumPy Arrays

Slicing allows you to select **subsets of an array** using ranges.

In [24]:
print(arr2d[0:2, 1:])

[[2 3]
 [5 6]]


## Functions for NumPy Arrays

**Functions for NumPy arrays** allow you to quickly perform mathematical and statistical operations on all elements of an array. NumPy provides many built-in functions for tasks such as calculating sums, means, minimums, maximums, and other numerical operations.

In [25]:
# Sum of all elements
print(np.sum(arr1d))
print(arr1d.sum())

# Mean (average) of the array
print(arr1d.mean())

# Mean (average) of rows of 2d array
print(arr2d.mean(axis=1))

10
10
2.5
[2. 5. 8.]


## Documentation

## Documentation

**Documentation** is written information that explains how a library, function, or piece of code works. Documentation typically describes what a function does, what inputs it expects, what it returns, and provides examples of how to use it.

In [26]:
# Viewing documentation for a NumPy function
import numpy as np
np.mean?

Signature:      
np.mean(
    a,
    axis=None,
    dtype=None,
    out=None,
    keepdims=<no value>,
    *,
    where=<no value>,
)
Call signature:  np.mean(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function mean at 0x000001CAD9C19750>
File:            c:\users\dbarthur\miniconda3\envs\tstat280\lib\site-packages\numpy\core\fromnumeric.py
Docstring:      
Compute the arithmetic mean along the specified axis.

Returns the average of the array elements.  The average is taken over
the flattened array by default, otherwise over the specified axis.
`float64` intermediate and return values are used for integer inputs.

Parameters
----------
a : array_like
    Array containing numbers whose mean is desired. If `a` is not an
    array, a conversion is attempted.
axis : None or int or tuple of ints, optional
    Axis or axes along which the means are computed. The default is to
    compute the mean of the flattened array.

    .. versionadded:: 1.7.0

    If 